--- 
abstract: RDBO storage layer for Handel 1.x
author: 
  - Christopher H. Laco
build_requires: 
  Directory::Scratch: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Handel-Storage-RDBO
no_index: 
  directory: 
    - inc
    - t
requires: 
  Clone: 0
  Handel: 1.00000
  Rose::DB: 0.734
  Rose::DB::Object: 0.764
  Rose::Object: 0.84
  Scalar::Util: 0
  perl: 5.8.1
tests: t/*.t t/*/*.t
version: 1.00002
