---
abstract: 'RDBO storage layer for Handel 1.x'
author:
  - 'Christopher H. Laco'
build_requires:
  Directory::Scratch: 0
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Handel-Storage-RDBO
no_index:
  directory:
    - inc
    - t
requires:
  Clone: 0.31
  Handel: 1.00013
  Rose::DB: 0.762
  Rose::DB::Object: 0.789
  Rose::Object: 0.858
  Scalar::Util: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.00003
